name: Docker

on:
  create:
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make docker
    - name: Push the Docker image
      run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} make docker-push
